[profile.default]
src = "src"
out = "out"
libs = ["lib"]
rpc_url = "sepolia" # Use as the default RPC endpoint

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
remappings = ["@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/"]

[rpc_endpoints]
sepolia = "https://shape-sepolia.g.alchemy.com/v2/aqWK2KOu_IzHiVM1Dsg_ToWN9QoOSOWF"
hedera_sepolia = "https://testnet.hashio.io/api"
anvil = "http://127.0.0.1:8545"
